### ISSUE TITLE
Attempt to read from field 'android.widget.TextView com.mobicage.rogerthat.NewsListAdapter$ViewHolder.reach' on a null object reference

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#145] opened 2017-05-02 09:26 UTC
```
2017-05-02 09:16:36 UTC
   (6 min ago)
***@gmail.com:em-be-***-demo
Count: 7 - Version: 0.2473
```

description: Bug!
Exception in SafeRunnable

errorMessage: java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView com.mobicage.rogerthat.NewsListAdapter$ViewHolder.reach' on a null object reference
```
	at com.mobicage.rogerthat.NewsListAdapter.updateView(NewsListAdapter.java:307)
	at com.mobicage.rogerthat.NewsActivity$14.safeRun(NewsActivity.java:604)
	at com.mobicage.rogerthat.util.system.SafeRunnable.run(SafeRunnable.java:50)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5458)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

mobicageVersion: 0.2473

occurenceCount: 7

platform: 1

platformVersion: Xiaomi/gemini/gemini:6.0.1/MXB48T/V8.1.2.0.MAAMIDI:user/release-keys (-) 23 (-) MI 5

**Comment by RubenMattan** [comment] 2017-05-02 09:29
duplicate of https://github.com/rogerthat-platform/rogerthat-android-client/issues/123

**Closed by RubenMattan** 2017-05-02 09:29 UTC
Labels: type_bug

**Comment by Kartik-21** [comment] 2019-12-26 17:40
assign the memory to the viewholder class

holder=new ViewHolder();
