### ISSUE TITLE
Avatar not positioned correctly in NativeBrandingView

### ISSUE THREAD

**Issue by ericCampos** [rogerthat-platform/rogerthat-android-client#115] opened 2017-03-03 14:59 UTC
Service: Sint-Truiden
Device: Motorola Nexus 6 (With "Font size" and "Display size" = small, in Settings/Display)

Just opened the service:
![screenshot_20170303-155021](https://cloud.githubusercontent.com/assets/11829006/23555660/0f22a2be-002a-11e7-9c81-c6bbd4af0dd8.png)

Opening "DigiMelding" and going back to the service menu:
![screenshot_20170303-155037](https://cloud.githubusercontent.com/assets/11829006/23555661/0f243516-002a-11e7-87ab-4bbc5c2778d8.png)

**Comment by bart-at-mobicage** [comment] 2017-03-07 10:10
duplicate of #112

**Closed by bart-at-mobicage** 2017-03-07 10:10 UTC
Labels: type_bug
